# -*- coding: utf-8 -*-
"""Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDJ_AvV6ypWgp2KYlcFYrzWZBedhJ71T
"""

# 1. SETUP: Install Libraries & Unzip Data
!pip install streamlit pyngrok plotly pandas scikit-learn -q

import os
import zipfile

# Unzip the "all_data.zip" if it exists
if os.path.exists("all_data.zip"):
    with zipfile.ZipFile("all_data.zip", 'r') as zip_ref:
        zip_ref.extractall("flight_data")
    print("✅ SUCCESS: Unzipped data into 'flight_data' folder.")
else:
    print("⚠️ WAITING: Please upload 'all_data.zip' to the sidebar first!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import glob
# import os
# import calendar
# from sklearn.ensemble import RandomForestRegressor
# 
# # --- PAGE CONFIG ---
# st.set_page_config(page_title="Airline Strategy Engine (Final + AI Select)", layout="wide")
# 
# # --- 1. DATA LOADER ---
# @st.cache_data
# def load_all_data():
#     files = glob.glob(os.path.join("flight_data", "*.csv"))
#     if not files: files = glob.glob("*.csv")
# 
#     if not files: return None
# 
#     print(f"🧠 Brain is processing {len(files)} data files...")
# 
#     df_list = []
#     for f in files:
#         try:
#             tmp = pd.read_csv(f)
#             tmp.columns = [c.upper() for c in tmp.columns]
# 
#             # FORCE NUMERIC
#             cols_to_fix = ['PASSENGERS', 'DISTANCE', 'DEPARTURES_PERFORMED', 'SEATS', 'MONTH', 'YEAR']
#             for col in cols_to_fix:
#                 if col in tmp.columns:
#                     tmp[col] = pd.to_numeric(tmp[col], errors='coerce').fillna(0)
# 
#             df_list.append(tmp)
#         except: continue
# 
#     if not df_list: return None
#     df = pd.concat(df_list, ignore_index=True)
# 
#     # CLEANING
#     if 'SEATS' in df.columns: df = df[df['SEATS'] > 0]
#     if 'DEPARTURES_PERFORMED' in df.columns: df = df[df['DEPARTURES_PERFORMED'] > 0]
# 
#     # MAPPING
#     if 'CARRIER_NAME' in df.columns: df['Airline_Label'] = df['CARRIER_NAME']
#     else: df['Airline_Label'] = df.get('UNIQUE_CARRIER', 'Unknown')
# 
#     df['Dest_Label'] = df.get('DEST_CITY_NAME', df.get('DEST', 'Unknown'))
# 
#     if 'DEST_COUNTRY_NAME' in df.columns: df['Region'] = df['DEST_COUNTRY_NAME']
#     elif 'DEST_STATE_ABR' in df.columns: df['Region'] = df['DEST_STATE_ABR']
#     else: df['Region'] = 'Global'
# 
#     return df
# 
# # --- 2. THE ANALYTICS BRAIN ---
# def run_financial_audit(df):
#     stats = df.groupby(['Region', 'Dest_Label', 'Airline_Label']).agg({
#         'PASSENGERS': 'sum', 'DISTANCE': 'mean',
#         'DEPARTURES_PERFORMED': 'sum', 'SEATS': 'sum'
#     }).reset_index()
# 
#     stats = stats[stats['PASSENGERS'] > 0]
# 
#     # Financial Formulas
#     stats['Yield'] = 0.6 * (stats['DISTANCE'] ** -0.15)
#     stats['Revenue'] = stats['PASSENGERS'] * (stats['DISTANCE'] * stats['Yield'])
#     stats['Cost'] = stats['DEPARTURES_PERFORMED'] * (stats['DISTANCE'] * 0.08 + 5500)
#     stats['Profit'] = stats['Revenue'] - stats['Cost']
#     stats['Margin'] = np.where(stats['Revenue'] > 0, (stats['Profit'] / stats['Revenue']) * 100, 0)
# 
#     # Efficiency Metrics
#     stats['Load_Factor'] = np.where(stats['SEATS'] > 0, (stats['PASSENGERS'] / stats['SEATS']) * 100, 0)
#     stats['Load_Factor'] = stats['Load_Factor'].clip(upper=100)
# 
#     # Monopoly Detector
#     city_totals = stats.groupby('Dest_Label')['PASSENGERS'].sum().reset_index()
#     city_totals.rename(columns={'PASSENGERS': 'City_Total'}, inplace=True)
#     stats = pd.merge(stats, city_totals, on='Dest_Label')
#     stats['Market_Share'] = (stats['PASSENGERS'] / stats['City_Total']) * 100
# 
#     hhi_calc = stats.copy()
#     hhi_calc['Share_Sq'] = hhi_calc['Market_Share'] ** 2
#     hhi_per_city = hhi_calc.groupby('Dest_Label')['Share_Sq'].sum().reset_index()
#     hhi_per_city.rename(columns={'Share_Sq': 'HHI_Score'}, inplace=True)
# 
#     stats = pd.merge(stats, hhi_per_city, on='Dest_Label')
#     conditions = [
#         (stats['HHI_Score'] < 1500),
#         (stats['HHI_Score'] >= 1500) & (stats['HHI_Score'] < 2500)
#     ]
#     stats['Competition_Status'] = np.select(conditions, ['⚔️ Price War', '⚠️ Concentrated'], default='👑 Monopoly')
# 
#     return stats
# 
# # --- 3. THE AI FORECAST BRAIN (Updated for Revenue) ---
# def run_ai_forecast(full_df, origin, dest, target_metric='PASSENGERS'):
#     # 1. Isolate the Route
#     route = full_df[(full_df['ORIGIN'] == origin) &
#                     (full_df['DEST_CITY_NAME'] == dest)].copy()
# 
#     if len(route) < 12: return None
# 
#     # 2. If predicting REVENUE, we must calculate it first
#     if target_metric == 'REVENUE':
#         # Apply the yield formula to every row
#         route['Yield'] = 0.6 * (route['DISTANCE'] ** -0.15)
#         route['Metric_Value'] = route['PASSENGERS'] * route['DISTANCE'] * route['Yield']
#     else:
#         route['Metric_Value'] = route['PASSENGERS']
# 
#     # 3. Group by Time
#     monthly = route.groupby(['YEAR', 'MONTH'])['Metric_Value'].sum().reset_index()
# 
#     # 4. Train AI
#     model = RandomForestRegressor(n_estimators=100, random_state=42)
#     model.fit(monthly[['YEAR', 'MONTH']], monthly['Metric_Value'])
# 
#     # 5. Predict Future
#     last_year = int(monthly['YEAR'].max())
#     future_dates = [{'YEAR': last_year + 1, 'MONTH': m} for m in range(1, 13)]
#     future_df = pd.DataFrame(future_dates)
#     future_df['Metric_Value'] = model.predict(future_df)
# 
#     monthly['Type'] = 'Historical'
#     future_df['Type'] = 'AI Forecast'
#     return pd.concat([monthly, future_df])
# 
# # ==========================================
# # 4. DASHBOARD UI
# # ==========================================
# df = load_all_data()
# 
# if df is not None:
#     st.title("✈️ Airline Network Strategic (AI Powered)")
# 
#     st.sidebar.header("🗓️ Time Filters")
#     years = sorted(df['YEAR'].unique().astype(int))
#     selected_year = st.sidebar.selectbox("Select Year", years, index=len(years)-1)
# 
#     time_mode = st.sidebar.radio("View Mode:", ["Full Year", "Specific Month"])
# 
#     filter_label = f"Year {selected_year}"
#     year_data = df[(df['YEAR'] == selected_year) & (df['ORIGIN'] == st.sidebar.selectbox("Select Hub", sorted(df['ORIGIN'].unique())))]
#     filtered_data = year_data.copy()
# 
#     if time_mode == "Specific Month":
#         month_map = {i: calendar.month_name[i] for i in range(1, 13)}
#         available_months = sorted(year_data['MONTH'].unique().astype(int))
#         if available_months:
#             selected_month = st.sidebar.selectbox("Select Month", available_months, format_func=lambda x: f"{x} - {month_map.get(x, str(x))}")
#             filtered_data = filtered_data[filtered_data['MONTH'] == selected_month]
#             filter_label = f"{month_map[selected_month]} {selected_year}"
#         else:
#             st.warning("No monthly data available.")
#             st.stop()
# 
#     if not filtered_data.empty:
#         audit = run_financial_audit(filtered_data)
# 
#         if not audit.empty:
#             total_profit = audit['Profit'].sum()
#             avg_load_factor = audit['Load_Factor'].mean()
#             # Top dest calculation for default value
#             top_dest = audit.sort_values('Profit', ascending=False).iloc[0]['Dest_Label']
# 
#             st.subheader(f"Performance: {filter_label}")
# 
#             c1, c2, c3, c4 = st.columns(4)
#             c1.metric("Net Profit", f"${total_profit/1e6:.1f}M")
#             c2.metric("Best Route", top_dest)
#             c3.metric("Avg Load Factor", f"{avg_load_factor:.1f}%")
#             c4.metric("Flights", f"{filtered_data['DEPARTURES_PERFORMED'].sum():,.0f}")
# 
#             tab1, tab2, tab3, tab4 = st.tabs(["🗺️ Profit Map", "📋 Full Data Grid", "🔥 Seasonality", "🔮 AI Forecast"])
# 
#             with tab1:
#                 plot_data = audit.dropna(subset=['PASSENGERS', 'Margin'])
#                 if not plot_data.empty:
#                     fig = px.treemap(plot_data, path=['Region', 'Competition_Status', 'Dest_Label', 'Airline_Label'],
#                                      values='PASSENGERS', color='Margin',
#                                      color_continuous_scale='RdYlGn', color_continuous_midpoint=0)
#                     st.plotly_chart(fig, use_container_width=True)
# 
#             with tab2:
#                 display_cols = ['Region', 'Dest_Label', 'Airline_Label', 'Competition_Status', 'PASSENGERS', 'SEATS', 'Load_Factor', 'Revenue', 'Cost', 'Profit', 'Margin']
#                 st.dataframe(audit[display_cols].sort_values('Profit', ascending=False)
#                              .style.format({'Profit': '${:,.0f}', 'Revenue': '${:,.0f}', 'Margin': '{:.1f}%', 'Load_Factor': '{:.1f}%'}))
# 
#             with tab3:
#                 top_20 = audit.sort_values('PASSENGERS', ascending=False).head(20)['Dest_Label'].unique()
#                 heatmap_source = year_data[year_data['Dest_Label'].isin(top_20)]
#                 heatmap_data = heatmap_source.pivot_table(index='Dest_Label', columns='MONTH', values='PASSENGERS', aggfunc='sum').fillna(0)
#                 fig_heat = px.imshow(heatmap_data, labels=dict(x="Month", y="Destination", color="Pax"), aspect="auto", color_continuous_scale='Viridis')
#                 st.plotly_chart(fig_heat, use_container_width=True)
# 
#             with tab4:
#                 st.subheader("🔮 Predictive Analytics Engine")
# 
#                 # --- NEW CONTROLS ---
#                 col_sel1, col_sel2 = st.columns(2)
# 
#                 with col_sel1:
#                     # 1. Select City (Defaults to Top Destination)
#                     available_dests = sorted(year_data['Dest_Label'].unique())
#                     default_idx = available_dests.index(top_dest) if top_dest in available_dests else 0
#                     forecast_dest = st.selectbox("Select Route to Predict:", available_dests, index=default_idx)
# 
#                 with col_sel2:
#                     # 2. Select Metric (Price/Revenue vs Demand)
#                     metric_choice = st.selectbox("Prediction Target:", ["Passenger Demand (Volume)", "Total Revenue (Financials)"])
#                     target_code = 'REVENUE' if "Revenue" in metric_choice else 'PASSENGERS'
# 
#                 if st.button(f"Generate {metric_choice} Forecast"):
#                     forecast_data = run_ai_forecast(df, filtered_data.iloc[0]['ORIGIN'], forecast_dest, target_code)
# 
#                     if forecast_data is not None:
#                         forecast_data['Date'] = pd.to_datetime(forecast_data[['YEAR', 'MONTH']].assign(DAY=1))
# 
#                         # Dynamic Formatting
#                         y_format = '${:,.0f}' if target_code == 'REVENUE' else '{:,.0f}'
#                         line_color = '#FF5733' if target_code == 'REVENUE' else '#00CC96'
# 
#                         fig_ai = px.line(forecast_data, x='Date', y='Metric_Value', color='Type',
#                                          title=f"AI Forecast for {forecast_dest}: {metric_choice}",
#                                          color_discrete_map={'Historical': 'gray', 'AI Forecast': line_color})
#                         st.plotly_chart(fig_ai, use_container_width=True)
#                     else:
#                         st.warning("Not enough historical data to generate a forecast for this route.")
#         else:
#             st.warning("Data found, but zero passengers recorded.")
#     else:
#         st.error(f"No flights found for {filter_label}")
# else:
#     st.info("Please upload 'all_data.zip'.")

# ==========================================
# 5. LAUNCHER
# ==========================================
import sys
from pyngrok import ngrok

# ⚠️ PASTE YOUR NGROK TOKEN HERE
ngrok.set_auth_token("37P7LKlsdAo14e6rtx2FkmqzTna_2mJdb1guYtckwgAFJ8okG")

# Kill old servers
!fuser -k 8501/tcp

# Start new server
get_ipython().system_raw('streamlit run app.py &')
public_url = ngrok.connect(8501).public_url
print(f"🚀 BRAIN IS LIVE: {public_url}")